# Tooggle for the two endpoints which are
# exposed. If not specified, it's assumed
# to be true.
options:
  program: false
  lowlevel: true

# List our endpoints that we'll use
# the "local" endpoint is always availble
endpoints:
  remote:
    url: http://10.0.3.129:8080
    token: {remotetoken}

# List of supported "programs"
# All of them support start/stop actions
programs:
  steam:
    include: steam.yml
    parameters:
      peerid: {peerid}
      parsec_exe: C:\Program Files\Parsec\parsecd.exe
      steam_exe: C:\Program Files (x86)\Steam\steam.exe
  jitsi:
    start:
      - method: execute
        arguments:
        - C:\Program Files\Google\Chrome\Application\chrome.exe
        - -kiosk
        - {videochannel_family}
      - method: delay
        arguments: 10
      - method: sendkeys
        arguments: "{{ENTER}}"
      - method: delay
        arguments: 1
      - method: sendkeys
        arguments: "{{ENTER}}"
